version: "3"

services:
  db:
    image: postgres
    container_name: todo-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  todo:
    image: todo
    restart: always
    container_name: todo-app
    env_file:
      - ./configs/todo-env.yaml
    ports:
      - "8000:8000"
